// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz3_nc-4erghOZ-pWIAgNmRBlPRvsbxes',
    appId: '1:643139183429:web:d8eb5732035b0543ac142c',
    messagingSenderId: '643139183429',
    projectId: 'define-todo-app',
    authDomain: 'define-todo-app.firebaseapp.com',
    storageBucket: 'define-todo-app.firebasestorage.app',
    measurementId: 'G-FQD5XCGX4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjV-CQddayFsEIN83ZETO4JuNQorMel-k',
    appId: '1:643139183429:android:72ddbd09be9c3bcbac142c',
    messagingSenderId: '643139183429',
    projectId: 'define-todo-app',
    storageBucket: 'define-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiXHH4yzGNYWYsxgr1kSGpstxd3hlVZJM',
    appId: '1:643139183429:ios:b791c061256fcb0fac142c',
    messagingSenderId: '643139183429',
    projectId: 'define-todo-app',
    storageBucket: 'define-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.defineTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiXHH4yzGNYWYsxgr1kSGpstxd3hlVZJM',
    appId: '1:643139183429:ios:b791c061256fcb0fac142c',
    messagingSenderId: '643139183429',
    projectId: 'define-todo-app',
    storageBucket: 'define-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.defineTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz3_nc-4erghOZ-pWIAgNmRBlPRvsbxes',
    appId: '1:643139183429:web:7dcd796e753cba4dac142c',
    messagingSenderId: '643139183429',
    projectId: 'define-todo-app',
    authDomain: 'define-todo-app.firebaseapp.com',
    storageBucket: 'define-todo-app.firebasestorage.app',
    measurementId: 'G-TXTGQ2RX1D',
  );
}
